local api = vim.api
local opt = vim.o

-- Vim color file
-- Name:       256_noir.vim
-- Maintainer: Andreas van Cranenburgh <andreas@unstable.nl>
-- Homepage:   https://github.com/andreasvc/vim-256noir/
--
-- Basically: dark background, numerals & errors red,
-- rest different shades of gray.
--
-- colors 232--250 are shades of gray, from dark to light;
-- 16=black, 255=white, 196=red, 88=darkred.

api.nvim_command 'highlight clear'
-- if version > 580
    -- no guarantees for version 5.8 and below, but this makes it stop
    -- complaining
    if vim.fn.exists('syntax_on') then
        api.nvim_command 'syntax reset'
    end
-- end
vim.g.colors_name = "256_noir"

-- OG
-- api.nvim_set_hl(0, 'Normal',          { fg = '#bcbcbc', bg = '#000000' })
-- api.nvim_set_hl(0, 'Keyword',         { fg = '#eeeeee', bg = '#000000' })
-- api.nvim_set_hl(0, 'Constant',        { fg = '#d0d0d0', bg = '#000000' })
-- api.nvim_set_hl(0, 'String',          { fg = '#8a8a8a', bg = '#000000' })
-- api.nvim_set_hl(0, 'Comment',         { fg = '#585858', bg = '#000000' })
-- api.nvim_set_hl(0, 'Number',          { fg = '#ff0000', bg = '#000000' })
-- api.nvim_set_hl(0, 'Error',           { fg = '#eeeeee', bg = '#870000' })
-- api.nvim_set_hl(0, 'ErrorMsg',        { fg = '#eeeeee', bg = '#af0000' })
-- api.nvim_set_hl(0, 'Search',          { fg = '#8a8a8a', bg = '#303030' })
-- api.nvim_set_hl(0, 'IncSearch',       { fg = '#eeeeee', bg = '#8a8a8a', reverse = true })
-- api.nvim_set_hl(0, 'DiffChange',      { fg = '#d70000', bg = '#eeeeee' })
-- api.nvim_set_hl(0, 'DiffText',        { fg = '#bcbcbc', bg = '#ff0000', bold = true })
-- api.nvim_set_hl(0, 'SignColumn',      { fg = '#af0000', bg = '#000000' })
-- api.nvim_set_hl(0, 'SpellBad',        { fg = '#eeeeee', bg = '#870000', undercurl = true })
-- api.nvim_set_hl(0, 'SpellCap',        { fg = '#eeeeee', bg = '#af0000' })
-- api.nvim_set_hl(0, 'SpellRare',       { fg = '#af0000', bg = '#000000' })
-- api.nvim_set_hl(0, 'WildMenu',        { fg = '#585858', bg = '#eeeeee' })
-- api.nvim_set_hl(0, 'Pmenu',           { fg = '#eeeeee', bg = '#585858' })
-- api.nvim_set_hl(0, 'PmenuThumb',      { fg = '#080808', bg = '#585858' })
-- api.nvim_set_hl(0, 'SpecialKey',      { fg = '#000000', bg = '#eeeeee' })
-- api.nvim_set_hl(0, 'MatchParen',      { fg = '#000000', bg = '#585858' })
-- api.nvim_set_hl(0, 'CursorLine',      {                 bg = '#121212' })
-- api.nvim_set_hl(0, 'StatusLine',      { fg = '#8a8a8a', bg = '#000000', bold = true, reverse = true })
-- api.nvim_set_hl(0, 'StatusLineNC',    { fg = '#303030', bg = '#000000', reverse = true })
-- api.nvim_set_hl(0, 'Visual',          { fg = '#bcbcbc', bg = '#000000', reverse = true })
-- api.nvim_set_hl(0, 'TermCursor',      {                                 reverse = true })

-- api.nvim_set_hl(0, 'Boolean',        { force = true, link = 'Normal' })
-- api.nvim_set_hl(0, 'Delimiter',      { force = true, link = 'Normal' })
-- api.nvim_set_hl(0, 'Identifier',     { force = true, link = 'Normal' })
-- api.nvim_set_hl(0, 'Title',          { force = true, link = 'Normal' })
-- api.nvim_set_hl(0, 'Debug',          { force = true, link = 'Normal' })
-- api.nvim_set_hl(0, 'Exception',      { force = true, link = 'Normal' })
-- api.nvim_set_hl(0, 'FoldColumn',     { force = true, link = 'Normal' })
-- api.nvim_set_hl(0, 'Macro',          { force = true, link = 'Normal' })
-- api.nvim_set_hl(0, 'ModeMsg',        { force = true, link = 'Normal' })
-- api.nvim_set_hl(0, 'MoreMsg',        { force = true, link = 'Normal' })
-- api.nvim_set_hl(0, 'Question',       { force = true, link = 'Normal' })
-- api.nvim_set_hl(0, 'Conditional',    { force = true, link = 'Keyword' })
-- api.nvim_set_hl(0, 'Statement',      { force = true, link = 'Keyword' })
-- api.nvim_set_hl(0, 'Operator',       { force = true, link = 'Keyword' })
-- api.nvim_set_hl(0, 'Structure',      { force = true, link = 'Keyword' })
-- api.nvim_set_hl(0, 'Function',       { force = true, link = 'Keyword' })
-- api.nvim_set_hl(0, 'Include',        { force = true, link = 'Keyword' })
-- api.nvim_set_hl(0, 'Type',           { force = true, link = 'Keyword' })
-- api.nvim_set_hl(0, 'Typedef',        { force = true, link = 'Keyword' })
-- api.nvim_set_hl(0, 'Todo',           { force = true, link = 'Keyword' })
-- api.nvim_set_hl(0, 'Label',          { force = true, link = 'Keyword' })
-- api.nvim_set_hl(0, 'Define',         { force = true, link = 'Keyword' })
-- api.nvim_set_hl(0, 'DiffAdd',        { force = true, link = 'Keyword' })
-- api.nvim_set_hl(0, 'diffAdded',      { force = true, link = 'Keyword' })
-- api.nvim_set_hl(0, 'diffCommon',     { force = true, link = 'Keyword' })
-- api.nvim_set_hl(0, 'Directory',      { force = true, link = 'Keyword' })
-- api.nvim_set_hl(0, 'PreCondit',      { force = true, link = 'Keyword' })
-- api.nvim_set_hl(0, 'PreProc',        { force = true, link = 'Keyword' })
-- api.nvim_set_hl(0, 'Repeat',         { force = true, link = 'Keyword' })
-- api.nvim_set_hl(0, 'Special',        { force = true, link = 'Keyword' })
-- api.nvim_set_hl(0, 'SpecialChar',    { force = true, link = 'Keyword' })
-- api.nvim_set_hl(0, 'StorageClass',   { force = true, link = 'Keyword' })
-- api.nvim_set_hl(0, 'SpecialComment', { force = true, link = 'String' })
-- api.nvim_set_hl(0, 'CursorLineNr',   { force = true, link = 'String' })
-- api.nvim_set_hl(0, 'Character',      { force = true, link = 'Number' })
-- api.nvim_set_hl(0, 'Float',          { force = true, link = 'Number' })
-- api.nvim_set_hl(0, 'Tag',            { force = true, link = 'Number' })
-- api.nvim_set_hl(0, 'Folded',         { force = true, link = 'Number' })
-- api.nvim_set_hl(0, 'WarningMsg',     { force = true, link = 'Number' })
-- api.nvim_set_hl(0, 'iCursor',        { force = true, link = 'SpecialKey' })
-- api.nvim_set_hl(0, 'SpellLocal',     { force = true, link = 'SpellCap' })
-- api.nvim_set_hl(0, 'LineNr',         { force = true, link = 'Comment' })
-- api.nvim_set_hl(0, 'NonText',        { force = true, link = 'Comment' })
-- api.nvim_set_hl(0, 'DiffDelete',     { force = true, link = 'Comment' })
-- api.nvim_set_hl(0, 'diffRemoved',    { force = true, link = 'Comment' })
-- api.nvim_set_hl(0, 'PmenuSbar',      { force = true, link = 'Visual' })
-- api.nvim_set_hl(0, 'PmenuSel',       { force = true, link = 'Visual' })
-- api.nvim_set_hl(0, 'VisualNOS',      { force = true, link = 'Visual' })
-- api.nvim_set_hl(0, 'VertSplit',      { force = true, link = 'Visual' })
-- api.nvim_set_hl(0, 'Cursor',         { force = true, link = 'StatusLine' })
-- api.nvim_set_hl(0, 'Underlined',     { force = true, link = 'SpellRare' })
-- api.nvim_set_hl(0, 'rstEmphasis',    { force = true, link = 'SpellRare' })
-- api.nvim_set_hl(0, 'diffChanged',    { force = true, link = 'DiffChange' })

api.nvim_set_hl(0, 'Normal',        { fg = '#ffffff', bg = '#000000' })
api.nvim_set_hl(0, 'Keyword',       { fg = '#eeeeee', bg = '#000000' })
api.nvim_set_hl(0, 'Constant',      { fg = '#d0d0d0', bg = '#000000' })
api.nvim_set_hl(0, 'String',        { fg = '#8a8a8a', bg = '#000000' })
api.nvim_set_hl(0, 'Comment',       { fg = '#585858', bg = '#000000' })
api.nvim_set_hl(0, 'Number',        { fg = '#ff0000', bg = '#000000' })
api.nvim_set_hl(0, 'Error',         { fg = '#eeeeee', bg = '#870000' })
api.nvim_set_hl(0, 'ErrorMsg',      { fg = '#eeeeee', bg = '#af0000' })
api.nvim_set_hl(0, 'Search',        { fg = '#8a8a8a', bg = '#303030' })
api.nvim_set_hl(0, 'IncSearch',     { fg = '#eeeeee', bg = '#8a8a8a', reverse = true })
api.nvim_set_hl(0, 'DiffChange',    { fg = '#d70000', bg = '#eeeeee' })
api.nvim_set_hl(0, 'DiffText',      { fg = '#bcbcbc', bg = '#ff0000', bold = true })
api.nvim_set_hl(0, 'SignColumn',    { fg = '#af0000', bg = '#000000' })
api.nvim_set_hl(0, 'SpellBad',      { fg = '#eeeeee', bg = '#870000', undercurl = true })
api.nvim_set_hl(0, 'SpellCap',      { fg = '#eeeeee', bg = '#af0000' })
api.nvim_set_hl(0, 'SpellRare',     { fg = '#af0000', bg = '#000000' })
api.nvim_set_hl(0, 'WildMenu',      { fg = '#585858', bg = '#eeeeee' })
api.nvim_set_hl(0, 'Pmenu',         { fg = '#eeeeee', bg = '#101010' })
api.nvim_set_hl(0, 'PmenuThumb',    { fg = '#080808', bg = '#585858' })
api.nvim_set_hl(0, 'SpecialKey',    { fg = '#000000', bg = '#eeeeee' })
api.nvim_set_hl(0, 'MatchParen',    { fg = '#000000', bg = '#585858', underline = true })
api.nvim_set_hl(0, 'CursorLine',    {                 bg = '#121212' })
api.nvim_set_hl(0, 'StatusLine',    { fg = '#8a8a8a', bg = '#000000', bold = true, reverse = true })
api.nvim_set_hl(0, 'StatusLineNC',  { fg = '#303030', bg = '#000000', reverse = true })
api.nvim_set_hl(0, 'Visual',        { fg = '#bcbcbc', bg = '#000000', reverse = true })
api.nvim_set_hl(0, 'TermCursor',    {                                 reverse = true })
api.nvim_set_hl(0, 'Todo',          { fg = '#ffffff', bg = '#000000', underline = true })
api.nvim_set_hl(0, 'FoldColumn',    {                 bg = '#000000' })

api.nvim_set_hl(0, 'Boolean',       { force = true, link = 'Normal' })
api.nvim_set_hl(0, 'Delimiter',     { force = true, link = 'Normal' })
api.nvim_set_hl(0, 'Identifier',    { force = true, link = 'Normal' })
api.nvim_set_hl(0, 'Title',         { force = true, link = 'Normal' })
api.nvim_set_hl(0, 'Debug',         { force = true, link = 'Normal' })
api.nvim_set_hl(0, 'Exception',     { force = true, link = 'Normal' })
api.nvim_set_hl(0, 'Macro',         { force = true, link = 'Normal' })
api.nvim_set_hl(0, 'ModeMsg',       { force = true, link = 'Normal' })
api.nvim_set_hl(0, 'MoreMsg',       { force = true, link = 'Normal' })
api.nvim_set_hl(0, 'Question',      { force = true, link = 'Normal' })
api.nvim_set_hl(0, 'Conditional',   { force = true, link = 'Keyword' })
api.nvim_set_hl(0, 'Statement',     { force = true, link = 'Keyword' })
api.nvim_set_hl(0, 'Operator',      { force = true, link = 'Keyword' })
api.nvim_set_hl(0, 'Structure',     { force = true, link = 'Keyword' })
api.nvim_set_hl(0, 'Function',      { force = true, link = 'Keyword' })
api.nvim_set_hl(0, 'Include',       { force = true, link = 'Keyword' })
api.nvim_set_hl(0, 'Type',           { force = true, link = 'Keyword' })
api.nvim_set_hl(0, 'Typedef',       { force = true, link = 'Keyword' })
api.nvim_set_hl(0, 'Label',         { force = true, link = 'Keyword' })
api.nvim_set_hl(0, 'Define',        { force = true, link = 'Keyword' })
api.nvim_set_hl(0, 'Directory',     { force = true, link = 'Keyword' })
api.nvim_set_hl(0, 'PreCondit',     { force = true, link = 'Keyword' })
api.nvim_set_hl(0, 'PreProc',       { force = true, link = 'Keyword' })
api.nvim_set_hl(0, 'Repeat',        { force = true, link = 'Keyword' })
api.nvim_set_hl(0, 'Special',       { force = true, link = 'Keyword' })
api.nvim_set_hl(0, 'SpecialChar',   { force = true, link = 'Keyword' })
api.nvim_set_hl(0, 'StorageClass',  { force = true, link = 'Keyword' })
api.nvim_set_hl(0, 'SpecialComment',{ force = true, link = 'String' })
api.nvim_set_hl(0, 'CursorLineNr',  { force = true, link = 'String' })
api.nvim_set_hl(0, 'Character',     { force = true, link = 'Number' })
api.nvim_set_hl(0, 'Float',         { force = true, link = 'Number' })
api.nvim_set_hl(0, 'Tag',           { force = true, link = 'Number' })
api.nvim_set_hl(0, 'Folded',        { force = true, link = 'Number' })
api.nvim_set_hl(0, 'WarningMsg',    { force = true, link = 'Number' })
api.nvim_set_hl(0, 'iCursor',       { force = true, link = 'SpecialKey' })
api.nvim_set_hl(0, 'SpellLocal',    { force = true, link = 'SpellCap' })
api.nvim_set_hl(0, 'LineNr',        { force = true, link = 'Comment' })
api.nvim_set_hl(0, 'NonText',       { force = true, link = 'Comment' })
api.nvim_set_hl(0, 'PmenuSbar',     { force = true, link = 'Visual' })
api.nvim_set_hl(0, 'PmenuSel',      { force = true, link = 'Visual' })
api.nvim_set_hl(0, 'VisualNOS',     { force = true, link = 'Visual' })
api.nvim_set_hl(0, 'VertSplit',     { force = true, link = 'Visual' })
api.nvim_set_hl(0, 'Cursor',        { force = true, link = 'StatusLine' })
api.nvim_set_hl(0, 'Underlined',    { force = true, link = 'SpellRare' })
api.nvim_set_hl(0, 'DiffAdd',       { force = true, link = 'Keyword' })
api.nvim_set_hl(0, 'DiffDelete',    { force = true, link = 'Comment' })
